name: 编译luci-app-cloudflared

on:
  workflow_dispatch:

jobs:
 build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: 下载工具链
        run: |
          sudo timedatectl set-timezone Asia/Shanghai
          wget -qO /opt/sdk.tar.xz https://downloads.openwrt.org/releases/22.03.5/targets/rockchip/armv8/openwrt-sdk-22.03.5-rockchip-armv8_gcc-11.2.0_musl.Linux-x86_64.tar.xz
          tar -xJf /opt/sdk.tar.xz -C /opt
          git clone https://github.com/lmq8267/luci-app-cloudflared.git /opt/cf
          cd /opt/openwrt-sdk*/package
          cp -R /opt/cf/luci-app-cloudflared .
          cp -R /opt/cf/luci-app-cloudflared_En .
          cd /opt/openwrt-sdk*
          ./scripts/feeds update -a
          make defconfig
      - name: 开始编译
        run: |
          cd /opt/openwrt-sdk*
          make package/luci-app-cloudflared/compile V=s -j1
          make package/luci-app-cloudflared_En/compile V=s -j1
          cd /opt/openwrt-sdk*/bin/packages/aarch64_generic/base
          ls
          #mv *.ipk luci-app-cloudflared_all.ipk
          echo "build_time=$(date '+%Y年%m月%d日%H:%M:%S' | jq -sRr @uri)" >> $GITHUB_ENV
          echo "tag=$(date '+%Y-%m-%d')" >> $GITHUB_ENV
      - name: 发布
        uses: softprops/action-gh-release@v1
        with:
            token: ${{ secrets.c8 }}
            body: |
             > ### ![](https://img.shields.io/badge/%E7%BC%96%E8%AF%91%E6%97%B6%E9%97%B4-${{ env.build_time }}-8267?logo=github&labelColor=%E9%A1%BB)![](https://img.shields.io/github/downloads/lmq8267/luci-app-cloudflared/${{ env.tag }}/total?label=%E4%B8%8B%E8%BD%BD%E6%AC%A1%E6%95%B0&logo=github)

             English：luci-app-cloudflared_En_1.0_all.ipk
             中文版：luci-app-cloudflared_1.0_all.ipk
             
            tag_name: ${{ env.tag }}
            files: /opt/openwrt-sdk*/bin/packages/aarch64_generic/base/*
     
