name: 编译luci-app-cloudflared

on:
  workflow_dispatch:

jobs:
 build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: 下载工具链
        run: |
          sudo timedatectl set-timezone Asia/Shanghai
          wget -qO /opt/sdk.tar.xz https://downloads.openwrt.org/releases/24.10.1/targets/x86/generic/openwrt-sdk-24.10.1-x86-generic_gcc-13.3.0_musl.Linux-x86_64.tar.zst
          tar -xJf /opt/sdk.tar.xz -C /opt
          git clone https://github.com/chea0214/luci-app-cloudflared /opt/cf
          cd /opt/openwrt-sdk*/package
          cp -R /opt/cf/luci-app-cloudflared .
          cd /opt/openwrt-sdk*
          ./scripts/feeds update -a
          make defconfig
      - name: 开始编译
        run: |
          cd /opt/openwrt-sdk*
          make package/luci-app-cloudflared/compile V=s -j1
          cd /opt/openwrt-sdk*/bin/packages/aarch64_generic/base
          ls
          #mv *.ipk luci-app-cloudflared_all.ipk
          echo "build_time=$(date '+%Y年%m月%d日%H:%M:%S' | jq -sRr @uri)" >> $GITHUB_ENV
          echo "tag=$(date '+%Y-%m-%d')" >> $GITHUB_ENV
      - name: 发布
        uses: softprops/action-gh-release@v1
        with:
            tag_name: ${{ env.tag }}
            files: /opt/openwrt-sdk*/bin/packages/aarch64_generic/base/*
     
